### ISSUE TITLE
Invalid XML not well-formed (invalid token)

### ISSUE THREAD

**Issue by jzaruba** [alek-sys/sublimetext_indentxml#101]
I am getting invalid token error at 16:82 of the attached file.
I see nothing suspicious there, I have also reformated the same file in IntelliJ Idea w/o a problem.

[templates.xml.txt](https://github.com/alek-sys/sublimetext_indentxml/files/1098974/templates.xml.txt)

**Comment by alek-sys** [comment]
It feels like this is the same problem with CDATA as in #57

Currently `xml.minidom` doesn't support CDATA section fully, some tokens there just break parsing. I'm currently looking what can be done with this, starting of test coverage of existing functionality and potential switch from xml.minidom to lxml. However at the moment there is no quick fix for this, sorry!

**Comment by alek-sys** [comment]
Fixed by a4b25ef0931f113b85b73fe5003a53839053736c
