### ISSUE TITLE
Feature Request: Un-Indent

### ISSUE THREAD

**Issue by tschinz** [alek-sys/sublimetext_indentxml#103]
I would like to have 2 operations. "intend" and "un-indent", this means going back and forth between the two views.
Is this possible?
thanks for the plugin

**Comment by TheChrisPratt** [comment]
Ctrl-Z will undo the indent.  If you're thinking you should be able to do
other things and then "reverse indent", that would require the plug-in to
remember the ugly indenting of your whole file just in case you wanted to
undo all it's hard work.  That seems like a terrible waste of memory.
  (*Chris*)

**Comment by alek-sys** [comment]
Ctrl+Z does the job, I think making this a plugin feature is a bit too much.
