### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by derMart** [alek-sys/sublimetext_indentxml#108]
I am trying to install indent xml on Sublime 3 build 3143 on Ubuntu 16.04
After clicking Package Control -> Install Package -> Indent XML (v2017.11.21.19.48.12) the popup just disappears with nothing else happening.

How to install this plugin?

**Comment by alek-sys** [comment]
There is no output from plugin installation, so probably everything is fine. Can you please check if you have a 'Selection -> Format' commands available?

**Comment by derMart** [comment]
No, not there. Also it is not listed under 'Preferences -> Package Settings' (assuming every package has an entry there?)
Is there a log output file or run time console? Where to find that?

**Comment by derMart** [comment]
After clicking ... -> Install Package -> Indent XML i get this in the console:
`Traceback (most recent call last):
  File "package_control.package_installer in /local/home/lmartin/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 154, in on_done
  File "package_control.package_disabler in /local/home/lmartin/.config/sublime-text-3/Installed Packages/Package Control.sublime-package", line 76, in disable_packages
ImportError: No module named 'package_control'`

**Comment by alek-sys** [comment]
It feels like this is a problem with Package Control itself, not Indent XML. 

You can try to install Indent XML manually - just clone git repo into packages folder (Preferences -> Browse Package will navigate to your packages folder). 

Also, you might ask how to fix package control at https://github.com/wbond/package_control
