### ISSUE TITLE
Make a more friendly Installation

### ISSUE THREAD

**Issue by padillla** [alek-sys/sublimetext_indentxml#109]
Come on, why cant this be installed like any other package control plugin?

A big mess for a freaking linter.  Every time I install sublime, I have to do this, like setting up a new processor core.
WHY?

**Comment by alek-sys** [comment]
Hey, thanks for feedback. 
This plugins is available in Package Control, search for 'indent xml' (as it is stated in README). If you have any problems with that - please let me know.

**Comment by padillla** [comment]
I see.

I followed a link in a txt file that opened after installing the plugin that stated that I should follow some very complicated instructions to finish installing it.

I tried reinstalling the plugin several times to show you but the damn txt didn't come up ever again.

Now i realized it was for XML lint, not this XML indent plugin.

My apologies for the rant. My bad.
