### ISSUE TITLE
Ubuntu: No module named pyexpat

### ISSUE THREAD

**Issue by stoune** [alek-sys/sublimetext_indentxml#16]
On Ubuntu 12.04.1 LTS I've received error:
`Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./indentxml.py", line 32, in run
  File "./indentxml.py", line 48, in indentxml
  File ".\xml\dom\minidom.py", line 1927, in parseString
  File ".\xml\dom\expatbuilder.py", line 32, in <module>
  File ".\xml\parsers\expat.py", line 4, in <module>
ImportError: No module named pyexpat`

Looks like Sublime distribution doesn’t include pyexpat module.
Default version of Python used in Ubuntu 12.04 is 2.7.3 so you can't reuse system modules.

**Comment by arenaux** [comment]
If you are in a 64bit system, try with "lib64" instead of "lib" : ln -s /usr/lib64/python2.6/ [Sublime Text dir]/lib/

Example : ln -s /usr/lib64/python2.6/ /opt/sublimetext/Sublime_Text_2/lib/

It works for me ;)

**Comment by skualos** [comment]
Solutions provided here did not work for me.
But following instructions from http://www.sublimerge.com/support.html fixed the issue on Ubuntu 14.04 x64:

    wget http://www.python.org/ftp/python/2.6.6/Python-2.6.6.tar.bz2
    tar xvjf Python-2.6.6.tar.bz2
    cd Python-2.6.6
    ./configure --prefix=/home/<your_user_name>/.local --enable-unicode=ucs4
    make && make install
    ln -s ~/.local/lib/python2.6 <Sublime Directory>/lib/python2.6

Restart Sublime Text 2

**Comment by AncientSwordRage** [comment]
Could this be included as a dep?

https://pypi.python.org/pypi/defusedexpat/

It's expat with vulnerabilities patched (defused). Seems more sensible than hot patching python 2.6 into the mix.

**Comment by colintsteele** [comment]
I have done ln -s ~/.local/lib/python2.7 /opt/sublime_text_2/lib/python2.7, and all of the preceding commands as told by @skualos from http://www.sublimerge.com/support.html but to no avail.  I am still seeing the error: ImportError: No module named pyexpat.  I have reinstalled python and doing the ln -s /usr/lib64 and ~/.local/lib64 and nothing has worked.  I've scoured the internet and all the fixes seem to be in doing this ln -s, but for me it is not working.

**Comment by fabiobozzo** [comment]
skualos tip worked for me. thanks

**Comment by bbartol** [comment]
What fixed this for me was:

`ln -svf  /usr/lib/python2.7/lib-dynload/pyexpat.arm-linux-gnueabihf.so pyexpat.so`
`sudo mv pyexpat.so /usr/lib/python2.7/lib-dynload/`

You could combine the above into one line, of course; but above is how I did it.

**Comment by alek-sys** [comment]
Seems like this is irrelevant anymore. I'm closing this for now, feel free to re-open if it still reproduces.
