### ISSUE TITLE
Fails to format xml if a CDATA tag contains an ampersand '&"

### ISSUE THREAD

**Issue by misprintt** [alek-sys/sublimetext_indentxml#18]
The following example doesn't format because of the an '&' inside of a CDATA tag

```
<Data>
<Element><![CDATA[&]]>
</Element>
</Data>
```

Details
- IndentXML v2012.07.30.06.34.20 (via package control)
- OXS 10.8

**Comment by alek-sys** [comment]
Fixed by a4b25ef0931f113b85b73fe5003a53839053736c
