### ISSUE TITLE
doesn't work for other XML syntax schemes like XAML, XSL

### ISSUE THREAD

**Issue by bitbonk** [alek-sys/sublimetext_indentxml#29]
Currently there seems to be a hard check whether the current syntax setting is "XML". If it is not the case the "Format XML" menu entry is disabled.

 But there a are a lot of other syntax schemes  that are XML too and where the "Format XML" still makes sense. Such as XAML (can be installed with package control) or XSL (included out of the box).

**Comment by alek-sys** [comment]
It tries to detect syntax now (if it starts with < - treat it as XML). However, you can always set syntax (Ctrl+Shift+P) and then run Indent command again.
