### ISSUE TITLE
XML in one line getting no element found, when XML is invalid

### ISSUE THREAD

**Issue by JimBarrows** [alek-sys/sublimetext_indentxml#54]
Here's the XML in question:
<OTA_HotelResRQ xmlns="http://www.opentravel.org/OTA/2003/05" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" EchoToken="27516798AC15283F6F96295746FA0774" PrimaryLangID="de-DE" ResStatus="Book" Target="Production" TimeStamp="2014-03-07T19:06:46+01:00" TransactionIdentifier="1236213" Version="1.003" xsi:schemaLocation="http://www.opentravel.org/OTA/2003/05 OTA_HotelResRQ.xsd">                <POS>                    <Source>                        <BookingChannel Type="7">                            <CompanyName Code="A217"/>                        </BookingChannel>                    </Source>                </POS>                <HotelReservations>                    <HotelReservation>                        <RoomStays>                            <RoomStay>                                <RoomTypes>                                    <RoomType NumberOfUnits="1" RoomTypeCode="2118179"/>                                </RoomTypes>                                <RoomRates>                                    <RoomRate BookingCode="B1KDOIC">                                    <Rates>                                    <Rate>                                    <Base AmountAfterTax="133.52" AmountBeforeTax="133.52" CurrencyCode="EUR" DecimalPlaces="2"/>                                    <Total AmountAfterTax="133.52" AmountBeforeTax="133.52" CurrencyCode="EUR" DecimalPlaces="2"/>                                    </Rate>                                    </Rates>                                    </RoomRate>                                </RoomRates>                                <GuestCounts>                                    <GuestCount AgeQualifyingCode="1" Count="2"/>                                </GuestCounts>                                <TimeSpan End="2014-06-14" Start="2014-06-13"/>                                <BasicPropertyInfo ChainCode="BW" HotelCode="05546"/>                                <ResGuestRPHs>                                    <ResGuestRPH RPH="1"/>                                </ResGuestRPHs>                            </RoomStay>                        </RoomStays>                        <ResGuests>                            <ResGuest ResGuestRPH="1">                                <Profiles>                                    <ProfileInfo>                                    <Profile ProfileType="1" ShareAllMarketInd="No" ShareAllSynchInd="No">                                    <Customer>                                    <PersonName>                                    <GivenName>Martin</GivenName>                                    <Surname>Lechner</Surname>                                    </PersonName>                                    <Telephone AreaCityCode="0049170" PhoneNumber="4661420" PhoneUseType="4"/>                                    <Email>ma_lechner@web.de</Email>                                    <Address Type="1">                                    <AddressLine>Ziegeleistr. 42</AddressLine>                                    <CityName>Aichach</CityName>                                    <PostalCode>86551</PostalCode>                                    <County>DE</County>                                    <StateProv>GR</StateProv>                                    <CountryName>DE</CountryName>                                    </Address>                                    <CustLoyalty MembershipID="6006637428430565" ProgramID="GCC"/>                                    </Customer>                                    </Profile>                                    </ProfileInfo>                                </Profiles>                            </ResGuest>                        </ResGuests>                        <ResGlobalInfo>                            <Guarantee GuaranteeCode="GCC">                                <GuaranteesAccepted>                                    <GuaranteeAccepted>

**Comment by alek-sys** [comment]
I'm just cleaning up old issues. If this issue is still relevant - feel free to re-open.
