### ISSUE TITLE
Strange New Lines in Sublime Text 3

### ISSUE THREAD

**Issue by Woozar** [alek-sys/sublimetext_indentxml#56]
I got an xml that contains elements like this:
&lt;version&gt;
  1
&lt;/version&gt;

I expect them to be converted to     
&lt;version&gt;1&lt;/version&gt;

 like in V2 but it results in
&lt;version&gt;1
  &lt;/version&gt;

Not sure if i missed some config here.

**Comment by alek-sys** [comment]
I'd say this is excepted behavior - you text is exactly '1<new line>' so formatter just keeps that. I think modification of content in any way is not a good idea.
