### ISSUE TITLE
xml.parsers.expat.ExpatError: not well-formed 

### ISSUE THREAD

**Issue by auranetworks** [alek-sys/sublimetext_indentxml#58]
import socket
import sys, os
import xmltodict,json

try:
	s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
 	print "socket successfully created"
except socket.error as err:
	print "socket creation failed with error %s" %(err)

port = 8000

s.connect(('127.0.0.1', port))

s.send('GET /search?c=main&q=narendra+modi&format=xml&quick=1&hasmime=1 HTTP/1.1	Host: 127.0.0.1:8000  User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:20.0) Gecko/20100101 Firefox/20.0  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-US,en;q=0.5  Accept-Encoding: gzip, deflate  Referer: http://127.0.0.1:8000/search?c=main&q=nagesh  Connection: keep-alive If-Modified-Since: Thu, 05 Jun 2014 06:18:10 GMT\r\n\r\n')

data = '';
while True:
	data = data + s.recv(1024)
	if not s.recv(1024):break

var = data.find('\r\n\r\n')
xmldata = (data[var+4:])
result = xmltodict.parse(xmldata)
jdata = json.dumps(result) 
jsonObj = json.loads(jdata)
print jsonObj['response']['result']
print '\n'
s.close()
--------------------------------------------------------------------
o/p is :-1: 

socket successfully created
Traceback (most recent call last):
  File "result.py", line 24, in <module>
    result = xmltodict.parse(xmldata)
  File "/usr/local/lib/python2.6/dist-packages/xmltodict.py", line 248, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 11, column 6

**Comment by alek-sys** [comment]
Sorry, I don't quite understand how is it related to a plugin?
Seems like you are trying to parse json / xml from some web-server response? Please refer to xml.minidom and json Python libraries documentation.
