### ISSUE TITLE
Add option to have both styles of empty tags <tag></tag> and <tag/>

### ISSUE THREAD

**Issue by carlosedp** [alek-sys/sublimetext_indentxml#68]
Currently when I reindent a XML that have empty tags, the plugin only supports the format:

    <avp name="Filter-Id" value="377"/>

It would be ideal if there is a setting to have the alternate format:

    <avp name="Filter-Id" value="377"></avp>

Thanks

**Comment by alek-sys** [comment]
Hi, sorry, I don't have any plans to implement it in near future. Feel free to submit PRs though!
