### ISSUE TITLE
Add a setting for enable format attributes for new line

### ISSUE THREAD

**Issue by wluo-talend** [alek-sys/sublimetext_indentxml#72]
if the tag have many attributes  it will format the tag into one line for now.
In this case may be every attributes formated into each line looks better.
e.g: <tag name="abc" age="tgg" nation="USA" ... >wluo</tag"
format into:
<tag
      name="abc"
      age="tgg"
      nation="USA"
    ...
>
wluo
</tag>

**Comment by alek-sys** [comment]
Hi,
sorry, but I don't have plans to implement it in nearest future. Feel free to submit pull-requests!
