### ISSUE TITLE
Configurable Indent

### ISSUE THREAD

**Issue by keab42** [alek-sys/sublimetext_indentxml#78]
Is there a way to control whether this indents as Tabs or Spaces and how many spaces it should use?

**Comment by alek-sys** [comment]
There will be no separate setting, plugin just uses indentation settings from current view. Just go to 'View' -> 'Indentation' menu and check 'Indent using spaces'.

**Comment by cers** [comment]
This doesn't appear to work as described above in my Sublime. I'm using Sublime 3 build 3083 (stable). Here the command "Indent JSON" always uses 4 spaces, regardless of configured Tab Size, or if I've selected to indent with tabs.

**Comment by chbrandao** [comment]
@cers I tried to contact you by e-mail (cers at geeksbynature dot dk), with subject Inquiry. My e-mail is paulooliveira at cers dot com.
