### ISSUE TITLE
Unable to ident XML with & inside tags

### ISSUE THREAD

**Issue by stava** [alek-sys/sublimetext_indentxml#81]
For example: 

<ITEM_ID>125</ITEM_ID><PRODUCTNAME>Hill & Dale Stellenbosch Chardonnay (6ks)</PRODUCTNAME><PRODUCT> Hill & Dale Stellenbosch Chardonnay (6ks)</PRODUCT>

throws error: xml.parsers.expat.ExpatError: not well-formed (invalid token): line 96, column 681

XML indent tools dont have such problem, please, can you check?

**Comment by alek-sys** [comment]
Hi, 
this is message is quite right - XML doesn't allow to have & in a text (http://stackoverflow.com/questions/11840981/are-characters-or-allowed-in-xml), it should be replaced to &amp;
