### ISSUE TITLE
Menu Format -> all items are disabled

### ISSUE THREAD

**Issue by phi1ipp** [alek-sys/sublimetext_indentxml#85]
trying to format but all sub-menu items are disabled

I'm using Sublime 3 on Linux Ubuntu 15.10 amd64

**Comment by alek-sys** [comment]
Check current view's syntax settings (bottom right corner), plugin is enabled for JSON / XML / Plain text

**Comment by phi1ipp** [comment]
It's XML in the corner

**Comment by alek-sys** [comment]
Does keyboard short-cut work? Ctrl+K+F?

**Comment by phi1ipp** [comment]
Looks like nope :(

**Comment by alek-sys** [comment]
Not sure how can I help then, sorry. Unless you want to help and do some debug - you need to look into function `check_enabled`. Also, please provide exact version of ST3

Would be nice to have couple screenshots if possible.

**Comment by phi1ipp** [comment]
So the version I use is 3, build 3083
![screenshot_2016-01-01_20-34-46](https://cloud.githubusercontent.com/assets/8225379/12072958/267be280-b0c7-11e5-9332-52b35caa0300.png)

**Comment by w4mu** [comment]
I have the same issue on Sublime Text 3 build 3103.

**Comment by alek-sys** [comment]
Not sure what I can do here. Feel free to re-open if there is anything I can do to help.
