### ISSUE TITLE
Dont installation plugin in ST3

### ISSUE THREAD

**Issue by blink2004** [alek-sys/sublimetext_indentxml#88]
Copy by Git to "/Sublime/Pachages/sublimetext_indentxml" plugin. Reopen Sublime Text 3 and nothink...
In Tools -> Command palette command "Indent XML" not found.
What is wrong?

**Comment by alek-sys** [comment]
Can you provide the following details:
- OS, exact version
- Sublime Text version
- steps I've done

By default, just copying of package should be enough, make sure you are using all correct paths (i.e. Pachages should be Packages) etc.
