### ISSUE TITLE
Package does not show up in Package Control

### ISSUE THREAD

**Issue by DanAtkinson** [alek-sys/sublimetext_indentxml#92]
I did a search for this package but when I type it in, it's not appearing.

![image](https://cloud.githubusercontent.com/assets/23440/16616861/e96ee614-4377-11e6-9e8d-1f154421f87a.png)

I tried leaving the default 'Package Control:' in, but still nothing:

![image](https://cloud.githubusercontent.com/assets/23440/16616868/f9b607a0-4377-11e6-9517-116f84f12ccf.png)

**Comment by alek-sys** [comment]
Based on the first screen shot - you are trying to find a plugin from main ST menu, not from package control search. To install 
1. Press Ctrl+Shift+P
2. Type "Package Control: Install Package"
3. Search for 'Indent XML'

**Comment by DanAtkinson** [comment]
Thanks for that!
