### ISSUE TITLE
Does not work with svg?

### ISSUE THREAD

**Issue by darkstarx** [alek-sys/sublimetext_indentxml#93]
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
       xmlns:i="&amp;ns_ai;"
       xmlns:dc="http://purl.org/dc/elements/1.1/"
       xmlns:cc="http://creativecommons.org/ns#"
       xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
       xmlns:svg="http://www.w3.org/2000/svg"
       xmlns="http://www.w3.org/2000/svg"
       xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
       xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
       version="1.1"
       id="Режим_изоляции"
       x="0px"
       y="0px"
       viewBox="0 0 84.511647 127.3"
       xml:space="preserve"
       inkscape:version="0.91 r13725"
       sodipodi:docname="logo.svg"
       width="84.51165"
       height="127.3">
              <metadata id="metadata3626">
                     rdf:RDF
                            <cc:Work about="">
                            /cc:Work
                     /rdf:RDF
              </metadata>
</svg>

Ctrl+k Ctrl+f

Result:
Invalid XML: not well-formatted (invalid token) line:19col:67
![snapshot-2](https://cloud.githubusercontent.com/assets/3534966/17474497/32852b2a-5d67-11e6-8b15-5c3f31bd7967.png)

**Comment by markskayff** [comment]
Same here for me.

**Comment by alek-sys** [comment]
Fixed by a4b25ef0931f113b85b73fe5003a53839053736c
