### ISSUE TITLE
Not working on mac.

### ISSUE THREAD

**Issue by Tutt1** [alek-sys/sublimetext_indentxml#94]
I finally solve this fuckin problem, which made me gone crazy nervous....
Non of the tutorials is working for mac users, if u don't want other people gone crazy u should update informations...
People with mac need to download whole file named "sublimetext_indentxml-master" and put it inside this folder:  machd -> user -> username -> Library -> application support -> sublime text 3 -> packages -> here paste the file, not in user, not in bz2 and after u open sublime text with some xml file, press cmd + shift + p and search for indent xml

**Comment by alek-sys** [comment]
Thanks for pointing this out. The recommended and supported way to install the plugin is via PackageControl, this is stated in README now.
