### ISSUE TITLE
larger data sets won't indent

### ISSUE THREAD

**Issue by Jrizzi1** [alek-sys/sublimetext_indentxml#98]
I have an xml doc with 300 or so elements with 3 sub elements for each

if i run indent xml it wont work, but if i break it up into parts it will

is there a set amount you can indent ?

**Comment by alek-sys** [comment]
Hi,
can you attach an example please? I don't think this is just about size, I've managed to format 30-40 MB files easily.

**Comment by alek-sys** [comment]
I'm going to close it for now, as data size is not a limit for a plugin (well, except for physical RAM limitations). Feel free to re-open it when you can provide an example.
